export const REGISTER_ADMIN = "users/register"
export const LOGIN_ADMIN = "users/login"
export const FETCH_ALL_TRANSACTION = "transaction/getall"
export const GET_ALL_ITEM = "items/getAll"
export const POST_NEW_ITEM = "items/add"
export const DELETE_ITEM = "items/delete"
export const UPDATE_ITEM = "items/update"
export const GET_ITEM_BY_ID = "items/getById"
